### ISSUE TITLE
not working on CentOS7

### ISSUE THREAD

**Issue by holdenger** [ukdtom/SRT2UTF-8.bundle#31]
Trying to get this work on CentOS7, but all tries are failing...

on windows or osx is everything working.

log file: http://pastebin.com/raw/D0AHMTsS

oh and permissions are OK.. i just tested it for user plex

**Comment by ukdtom** [comment]
Could you for a start try this?

At the top of the file __init__.py, you see a lot of imports

Add a line as:
`import locale`

Then in the start function of the same file, right after the line saying:
`Log.Info(L('Starting') + ' %s ' %(L('Srt2Utf-8')) + L('with a version of') + ' %s on %s' %(PLUGIN_VERSION, Platform.OS))`

add a line like:
`Log.Info('Locale is: ' + str(locale.getdefaultlocale()))`

In above, remember the indents, since otherwise Plex (Python) will complain

After that, restart PMS, and run SRT2UTF-8 again, and provide me a new log

/T

**Comment by ukdtom** [comment]
And adding.....I need the full log this time, and not a snip ;-)

**Comment by holdenger** [comment]
INFO (__init__:35) - Locale is: ('en_US', 'UTF-8')

Anyways, there is a full log :) 
https://www.dropbox.com/s/bhylcrucl0qfapk/com.plexapp.agents.srt2utf8.log?dl=1

**Comment by ukdtom** [comment]
I have no idea where you got this file from:
`Checking file: /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Media/localhost/f/6b154828640a83d019b36b15f3bc528eb8aea9f.bundle/Contents/Subtitle Contributions/com.plexapp.agents.opensubtitles/cs/7583078ebb6014bb111768358a87cb8a95a49129.srt.backup` 
but it's not supposed to be there, and is the one that fails.

Kinda suspect it' a backup that you made, with another user, and as such, the Plex user hasn't got the rights to it

/T
