### ISSUE TITLE
Forced Subtitle is not Supported

### ISSUE THREAD

**Issue by FHD100** [ukdtom/SRT2UTF-8.bundle#33]
Forced subtitles is not supported in any language
>exp: 
> sub_name.forced.srt
> sub_name.eng.forced.srt
 
@ukdtom

**Comment by ukdtom** [comment]
Hit a dead end on WT dev, do decided to put some love to SRT2UTF-8 instead, since this might be a low hanging fruit.

Please try this special build, that you have to install manually, and after testing, report back both good and bad.

https://github.com/ukdtom/SRT2UTF-8.bundle/archive/tommy-work.zip

**Comment by ukdtom** [comment]
And so far only for the syntax of:
`sub_name.forced.srt` to get an indication if I'm on the right track here

**Comment by ukdtom** [comment]
Heh...And checked the other combo....seems like that works as well ;)

**Comment by FHD100** [comment]
hey man, thanks for the fast respond on that issue. It works with forced subs! yaay :D
but.. ah sorry to break it down to you but i don't think it's that clever xD It doesn't work when you put the lang extension in front of it sadly 
> tried with:
> eng.forced.srt and ara.forced.srt

if you can add that too, that would be great! 
thanks again :)

**Comment by ukdtom** [comment]
Heh....

I tested with a file named `myMovie.forced.da.srt` and not `myMovie.da.forced.srt`

Updated the build, so please re-download and try again....
And do report back
